server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: qcm-service
          uri: lb://qcmservice
          predicates:
            - Path=/api/v1/qcm/**
            - Method=GET, POST, PUT, DELETE

          filters:
            - RewritePath=/cards/(?<segment>.*), /${segment}

        - id: question-service
          uri: lb://questionservice
          predicates:
            - Path=/api/v1/question/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RewritePath=/cards/(?<segment>.*), /${segment}

        - id: result-service
          uri: lb://resultservice
          predicates:
            - Path=/api/v1/result/**
            - Method=GET, POST, PUT, DELETE

          filters:
            - RewritePath=/cards/(?<segment>.*), /${segment}
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0
    exporter:
      zipkin:
        enabled: true
        endpoint: http://zipkin-server:9411/api/v2/spans
    enabled: true





