server:
  port: 0
info:
  app:
    name: "qcmservice"
    description: "To handle creating, updating, deleting, and managing questionnaires."
    version: "1.0.0"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qcm
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  profiles:
    active: native
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost