server:
  port: 0
info:
  app:
    name: "questionservice"
    description: "To manage individual questions and their answers."
    version: "1.0.0"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/questions
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  profiles:
    active: native
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
qcm:
  feign:
    url: http://localhost:8081
