server:
  port: 8082
info:
  app:
    name: "questionservice"
    description: "To manage individual questions and their answers."
    version: "1.0.0"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/questions
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  profiles:
    active: native

qcm:
  feign:
    url: http://localhost:8081
