server:
  port: 8083
info:
  app:
    name: "resultservice"
    description: "To handle the calculation and storage of users' responses and results."
    version: "1.0.0"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resultdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  profiles:
    active: native

qcm:
  feign:
    url: http://localhost:8081